// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /Users/tomasfernandezbouvier/Desktop/Thesis-model_implementation/AliAnalysisSelevTask.h;
#pragma link C++ defined_in "/Users/tomasfernandezbouvier/Desktop/Thesis-model_implementation/AliAnalysisSelevTask.cxx";

#endif
